namespace: microserviceA

public:
  - web:3000

services:
  web:
    image: node:4
    ports:
      - "3000:3000"
    volumes:
      - ..:/microserviceA
    working_dir: /microserviceA
    command: [npm, run, start-mocks]

setup:
  - cd .. && npm install
